:wrench: Added find data dir, and how commands are resolved

diff --git a/spx b/spx
--- a/spx
+++ b/spx
@@ -1,9 +1,19 @@
 #!/bin/bash
 PGM_BIN=spx
-PGM_VERSION=0.1.2
+PGM_VERSION=0.1.3
 
-# TODO(jfrias): determine dir
-DATA_DIR=.spx
+find_data_dir() {
+    local cwd=$(pwd)
+
+    while [ $cwd != "/" ]; do
+        local dir="$cwd/.spx"
+        if [ -d "$dir" ]; then
+            echo "$dir"
+            return
+        fi
+        cwd=$(dirname "$cwd")
+    done
+}
 
 # No command found
 if [ -z "$1" ]; then
@@ -26,24 +36,48 @@ done
 
 eval set -- "$_params"
 
-# Look in the current directory
-_cwd=$(pwd)
-if [ -x "$_cwd/$PGM_BIN-$1" ]; then
-    cmd="$_cwd/$PGM_BIN-$1"
+_sub_cmd=$1
+shift
 
-# Look in the parth
+# Environment defined data dir
+if [ -n "$SPHEX_DIR" ]; then
+    if [[ "$_sub_cmd" == "init" || -d "$SPHEX_DIR" ]]; then
+        DATA_DIR=$SPHEX_DIR
+    else
+        echo "SPHEX_DIR not found: \"$SPHEX_DIR\"."
+        exit 1
+    fi
+
+# Find data dir
 else
-    cmd=$(which "$PGM_BIN-$1" 2> /dev/null)
-    if [[ $? -ne 0 || ! -x "$cmd" ]]; then
-        echo "Invalid command $1."
+    if [ "$_sub_cmd" == "init" ]; then
+        DATA_DIR="$(pwd)/.spx"
+    else
+        DATA_DIR=$(find_data_dir)
+        if [ -z "$DATA_DIR" ]; then
+            echo "No repository found. Use \"$PGM_BIN init\""
+            exit 1
+        fi
+    fi
+fi
+
+
+# Check to see if sub-command is in path
+_sub_bin="$PGM_BIN-$_sub_cmd"
+_fullpath_sub_bin=$(which "$_sub_bin" 2> /dev/null)
+if [ $? -ne 0 ]; then
+    # else .. Look at the location where this command is
+    _fullpath_sub_bin="$(dirname $(realpath $0))/$_sub_bin"
+    if [ ! -x "$_fullpath_sub_bin" ]; then
+        echo "Invalid command $_fullpath_sub_bin."
         exit 1
     fi
 fi
 
+
 # Execute command
-shift
 (
 export PGM_BIN
 export DATA_DIR
-$cmd $*
+$_fullpath_sub_bin $*
 )
