:wrench: Output error messages to stderr

diff --git a/spx b/spx
--- a/spx
+++ b/spx
@@ -1,6 +1,5 @@
 #!/bin/bash
-
-INSTALL_DIR=$(dirname $(realpath "$0"))
+INSTALL_DIR=$(dirname $(realpath "${BASH_SOURCE[0]}"))
 source "$INSTALL_DIR/spx-core"
 
 usage() {
@@ -59,7 +58,7 @@ if [ -n "$SPHEX_DIR" ]; then
     if [[ "$_sub_cmd" == "init" || -d "$SPHEX_DIR" ]]; then
         DATA_DIR=$SPHEX_DIR
     else
-        echo "SPHEX_DIR not found: \"$SPHEX_DIR\"."
+        echo "SPHEX_DIR not found: \"$SPHEX_DIR\"." >&2
         exit 1
     fi
 
@@ -70,7 +69,7 @@ else
     else
         DATA_DIR=$(find_data_dir)
         if [ -z "$DATA_DIR" ]; then
-            echo "No repository found. Use \"$PGM_BIN init\""
+            echo "No repository found. Use \"$PGM_BIN init\"" >&2
             exit 1
         fi
     fi
@@ -84,7 +83,7 @@ if [ $? -ne 0 ]; then
     # else .. Look at the location where this command is
     _fullpath_sub_bin="$INSTALL_DIR/$_sub_bin"
     if [ ! -x "$_fullpath_sub_bin" ]; then
-        echo "Invalid command $_fullpath_sub_bin."
+        echo "Invalid command $_fullpath_sub_bin." >&2
         exit 1
     fi
 fi
diff --git a/spx-cat-file b/spx-cat-file
--- a/spx-cat-file
+++ b/spx-cat-file
@@ -14,7 +14,7 @@ while (( "$#" )); do
     case "$1" in
         -o)
             if [ -z "$2" ]; then
-                echo "No output file specified."
+                echo "No output file specified." >&2
                 exit 1
             else
                 _out_file=$2
@@ -36,7 +36,7 @@ while (( "$#" )); do
                 _sha=$1
                 shift
             else
-                echo "Extra argument \"$1\""
+                echo "Extra argument \"$1\"" >&2
                 exit 1
             fi
             ;;
@@ -44,14 +44,14 @@ while (( "$#" )); do
 done
 
 if [ ${#_sha} -lt 3 ]; then
-    echo "Must provide at least 3 characters of SHA."
+    echo "Must provide at least 3 characters of SHA." >&2
     exit 1
 
 # entire SHA
 elif [ ${#_sha} -eq 40 ]; then
     _object="$DATA_DIR/objects/${_sha:0:2}/${_sha:2}"
     if [ ! -r "$_object" ]; then
-        echo "Object \"$_object\" not readable."
+        echo "Object \"$_object\" not readable." >&2
         exit 1
     fi
 
@@ -60,12 +60,12 @@ else
     _object=$(find "$DATA_DIR/objects/${_sha:0:2}" -name "${_sha:2}*" -printf '%f\n')
 
     if [ -z "$_object" ]; then
-        echo "No object found matching \"$_sha\"."
+        echo "No object found matching \"$_sha\"." >&2
         exit 1
     fi
 
     if [ $(echo "$_object" | wc -l) -gt 1 ]; then
-        echo "More than one object found matching \"$_sha\"."
+        echo "More than one object found matching \"$_sha\"." >&2
         exit 1
     fi
 
@@ -78,7 +78,7 @@ zcat "$_object" > "$_blob"
 IFS= read -r -d '' _header < "$_blob"
 
 if [ "${_header:0:4}" != "blob" ]; then
-    echo "Corrupt object file, invalid signature."
+    echo "Corrupt object file, invalid signature." >&2
     exit 1
 fi
 
@@ -87,7 +87,7 @@ _expected_size=$(( $_header_len + ${_header:5} ))
 _size=$(stat --format %s "$_blob")
 
 if [ $_size -ne $_expected_size ]; then
-    echo "Corrupt object file, size missmatch."
+    echo "Corrupt object file, size missmatch." >&2
     exit 1
 fi
 
diff --git a/spx-ci b/spx-ci
--- a/spx-ci
+++ b/spx-ci
@@ -26,7 +26,7 @@ while (( "$#" )); do
     case "$1" in
         -m)
             if [ -z "$2" ]; then
-                echo "No message specified."
+                echo "No message specified." >&2
                 exit 1
             else
                 _message="$2"
@@ -53,7 +53,7 @@ while (( "$#" )); do
                 _file=$1
                 shift
             else
-                echo "Extra argument \"$1\""
+                echo "Extra argument \"$1\"" >&2
                 exit 1
             fi
             ;;
@@ -61,12 +61,12 @@ while (( "$#" )); do
 done
 
 if [[ -z "$_message" && -z "$_allow_empty_message" ]]; then
-    echo "No message for check-in."
+    echo "No message for check-in." >&2
     exit 1
 fi
 
 if [ ! -r "$_file" ]; then
-    echo "Cannot read file \"$_file\"."
+    echo "Cannot read file \"$_file\"." >&2
     exit 1
 fi
 
@@ -102,10 +102,6 @@ _author='Juan D Frias <juandfrias@gmail.com>'
 _file_sha=$("$PGM_BIN" hash-file --write "$_file")
 _date=$(date +"%s %z")
 _blob=$(mktemp "/tmp/$PGM_BIN-ci-file.XXXXXX")
-
-# Add parent
-TAB=$'\t'
-NL=$'\n'
 
 if [ -n "$_parent" ]; then
     echo "parent${TAB}$_parent" >> "$_blob"
diff --git a/spx-init b/spx-init
--- a/spx-init
+++ b/spx-init
@@ -28,14 +28,14 @@ if [ -n "$1" ]; then
             ;;
 
         *)
-            echo "Extra argument \"$1\"."
+            echo "Extra argument \"$1\"." >&2
             exit 1
             ;;
     esac
 fi
 
 if [ -d '.spx' ]; then
-    echo 'Repository already initialized.'
+    echo 'Repository already initialized.' >&2
     exit 1
 fi
 
@@ -43,7 +43,7 @@ _cwd=$(dirname $(pwd))
 while [ $_cwd != "/" ]; do
     dir="$_cwd/.spx"
     if [ -d "$dir" ]; then
-        echo "Cannot nest repositories. Repo found at \"$_cwd\""
+        echo "Cannot nest repositories. Repo found at \"$_cwd\"" >&2
         exit 1
     fi
     _cwd=$(dirname "$_cwd")
